import { 
  LayoutDashboard, Users, Link as LinkIcon, Settings, FileText, MessageSquare, 
  History, Star, Folder, Edit, Layout, Monitor, Clock, Calendar, 
  Inbox, Send, BarChart2, Plus, Table, HelpCircle, Tv, Zap,
  ArrowLeft, Shield, Radio, Check, Mic, Video, ChevronRight, 
  ChevronDown, ChevronUp, Filter, Trash2, Download, Upload,
  Search,
  Circle, Square, MoveRight, Type, Presentation, X
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Users: Users,
  Link: LinkIcon,
  Settings: Settings,
  FileText: FileText,
  Chat: MessageSquare,
  History: History,
  Star: Star,
  Folder: Folder,
  Edit: Edit,
  Board: Layout,
  Monitor: Monitor,
  Clock: Clock,
  Calendar: Calendar,
  Inbox: Inbox,
  Send: Send,
  Chart: BarChart2,
  Plus: Plus,
  Table: Table,
  Help: HelpCircle,
  Tv: Tv,
  Zap: Zap,
  TempraTv: Zap,
  ArrowLeft: ArrowLeft,
  Shield: Shield,
  Radio: Radio,
  Check: Check,
  Mic: Mic,
  Video: Video,
  Search: Search,
  ChevronRight: ChevronRight,
  ChevronDown: ChevronDown,
  ChevronUp: ChevronUp,
  Filter: Filter,
  Download: Download,
  Upload: Upload,
  Circle: Circle,
  Square: Square,
  ArrowRight: MoveRight,
  Text: Type,
  Role: Shield,
  Trash: Trash2,
  X: X
};
